export const destinations = [
  "Abu Dhabi, United Arab Emirates",
  "Accra, Ghana",
  "Addis Ababa, Ethiopia",
  "Adelaide, Australia",
  "Agra, India",
  "Ahmedabad, India",
  "Albuquerque, USA",
  "Alexandria, Egypt",
  "Algiers, Algeria",
  "Alicante, Spain",
  "Amman, Jordan",
  "Amsterdam, Netherlands",
  "Anchorage, USA",
  "Andorra la Vella, Andorra",
  "Antalya, Turkey",
  "Antananarivo, Madagascar",
  "Antwerp, Belgium",
  "Arusha, Tanzania",
  "Asheville, USA",
  "Ashgabat, Turkmenistan",
  "Asmara, Eritrea",
  "Astana, Kazakhstan",
  "Asuncion, Paraguay",
  "Athens, Greece",
  "Atlanta, USA",
  "Auckland, New Zealand",
  "Austin, USA",
  "Baku, Azerbaijan",
  "Bali, Indonesia",
  "Baltimore, USA",
  "Bamako, Mali",
  "Bandung, Indonesia",
  "Bangkok, Thailand",
  "Barcelona, Spain",
  "Basel, Switzerland",
  "Bath, United Kingdom",
  "Beijing, China",
  "Beirut, Lebanon",
  "Belfast, United Kingdom",
  "Belgrade, Serbia",
  "Belize City, Belize",
  "Bergen, Norway",
  "Berlin, Germany",
  "Bern, Switzerland",
  "Bilbao, Spain",
  "Birmingham, United Kingdom",
  "Bishkek, Kyrgyzstan",
  "Bogota, Colombia",
  "Bologna, Italy",
  "Bordeaux, France",
  "Boston, USA",
  "Brasilia, Brazil",
  "Bratislava, Slovakia",
  "Brazzaville, Republic of the Congo",
  "Brisbane, Australia",
  "Bruges, Belgium",
  "Brussels, Belgium",
  "Bucharest, Romania",
  "Budapest, Hungary",
  "Buenos Aires, Argentina",
  "Busan, South Korea",
  "Cairo, Egypt",
  "Calgary, Canada",
  "Cancun, Mexico",
  "Cape Town, South Africa",
  "Cardiff, United Kingdom",
  "Cartagena, Colombia",
  "Casablanca, Morocco",
  "Cebu City, Philippines",
  "Charleston, USA",
  "Charlotte, USA",
  "Chengdu, China",
  "Chennai, India",
  "Chiang Mai, Thailand",
  "Chicago, USA",
  "Christchurch, New Zealand",
  "Cincinnati, USA",
  "Cleveland, USA",
  "Cologne, Germany",
  "Colombo, Sri Lanka",
  "Copenhagen, Denmark",
  "Cordoba, Argentina",
  "Cusco, Peru",
  "Da Nang, Vietnam",
  "Dakar, Senegal",
  "Dallas, USA",
  "Damascus, Syria",
  "Dar es Salaam, Tanzania",
  "Delhi, India",
  "Denver, USA",
  "Detroit, USA",
  "Dhaka, Bangladesh",
  "Doha, Qatar",
  "Dresden, Germany",
  "Dubai, United Arab Emirates",
  "Dublin, Ireland",
  "Dubrovnik, Croatia",
  "Durban, South Africa",
  "Dusseldorf, Germany",
  "Edinburgh, United Kingdom",
  "Edmonton, Canada",
  "Florence, Italy",
  "Fort Lauderdale, USA",
  "Frankfurt, Germany",
  "Fukuoka, Japan",
  "Galway, Ireland",
  "Geneva, Switzerland",
  "Genoa, Italy",
  "George Town, Malaysia",
  "Glasgow, United Kingdom",
  "Gold Coast, Australia",
  "Granada, Spain",
  "Guadalajara, Mexico",
  "Guangzhou, China",
  "Guatemala City, Guatemala",
  "Hamburg, Germany",
  "Hanoi, Vietnam",
  "Harare, Zimbabwe",
  "Havana, Cuba",
  "Helsinki, Finland",
  "Ho Chi Minh City, Vietnam",
  "Hobart, Australia",
  "Hong Kong, China",
  "Honolulu, USA",
  "Houston, USA",
  "Hyderabad, India",
  "Innsbruck, Austria",
  "Interlaken, Switzerland",
  "Istanbul, Turkey",
  "Izmir, Turkey",
  "Jaipur, India",
  "Jakarta, Indonesia",
  "Jerusalem, Israel",
  "Johannesburg, South Africa",
  "Kampala, Uganda",
  "Kansas City, USA",
  "Karachi, Pakistan",
  "Kathmandu, Nepal",
  "Kigali, Rwanda",
  "Kingston, Jamaica",
  "Kobe, Japan",
  "Kolkata, India",
  "Krakow, Poland",
  "Kuala Lumpur, Malaysia",
  "Kyoto, Japan",
  "La Paz, Bolivia",
  "Lagos, Nigeria",
  "Lahore, Pakistan",
  "Las Vegas, USA",
  "Lausanne, Switzerland",
  "Lima, Peru",
  "Lisbon, Portugal",
  "Liverpool, United Kingdom",
  "Ljubljana, Slovenia",
  "London, United Kingdom",
  "Los Angeles, USA",
  "Luanda, Angola",
  "Lucerne, Switzerland",
  "Lyon, France",
  "Macau, China",
  "Madrid, Spain",
  "Malaga, Spain",
  "Male, Maldives",
  "Manchester, United Kingdom",
  "Manila, Philippines",
  "Marrakesh, Morocco",
  "Marseille, France",
  "Medellin, Colombia",
  "Melbourne, Australia",
  "Memphis, USA",
  "Mexico City, Mexico",
  "Miami, USA",
  "Milan, Italy",
  "Minneapolis, USA",
  "Monaco, Monaco",
  "Montreal, Canada",
  "Moscow, Russia",
  "Mumbai, India",
  "Munich, Germany",
  "Muscat, Oman",
  "Nairobi, Kenya",
  "Nanjing, China",
  "Nashville, USA",
  "Naples, Italy",
  "New Orleans, USA",
  "New York City, USA",
  "Nice, France",
  "Nicosia, Cyprus",
  "Osaka, Japan",
  "Oslo, Norway",
  "Ottawa, Canada",
  "Panama City, Panama",
  "Paris, France",
  "Perth, Australia",
  "Philadelphia, USA",
  "Phnom Penh, Cambodia",
  "Phoenix, USA",
  "Portland, USA",
  "Porto, Portugal",
  "Prague, Czechia",
  "Punta Cana, Dominican Republic",
  "Quebec City, Canada",
  "Quito, Ecuador",
  "Reykjavik, Iceland",
  "Riga, Latvia",
  "Rio de Janeiro, Brazil",
  "Rome, Italy",
  "Salzburg, Austria",
  "San Antonio, USA",
  "San Diego, USA",
  "San Francisco, USA",
  "San Jose, Costa Rica",
  "San Juan, Puerto Rico",
  "San Salvador, El Salvador",
  "Santiago, Chile",
  "Santo Domingo, Dominican Republic",
  "Sao Paulo, Brazil",
  "Sapporo, Japan",
  "Savannah, USA",
  "Seattle, USA",
  "Seoul, South Korea",
  "Seville, Spain",
  "Shanghai, China",
  "Shenzhen, China",
  "Siem Reap, Cambodia",
  "Singapore, Singapore",
  "Sofia, Bulgaria",
  "Split, Croatia",
  "Stockholm, Sweden",
  "Strasbourg, France",
  "Sydney, Australia",
  "Taipei, Taiwan",
  "Tallinn, Estonia",
  "Tashkent, Uzbekistan",
  "Tbilisi, Georgia",
  "Tel Aviv, Israel",
  "Thessaloniki, Greece",
  "Tirana, Albania",
  "Tokyo, Japan",
  "Toronto, Canada",
  "Toulouse, France",
  "Ubud, Indonesia",
  "Valencia, Spain",
  "Vancouver, Canada",
  "Venice, Italy",
  "Vienna, Austria",
  "Vientiane, Laos",
  "Vilnius, Lithuania",
  "Warsaw, Poland",
  "Washington, D.C., USA",
  "Wellington, New Zealand",
  "Winnipeg, Canada",
  "Yerevan, Armenia",
  "Zagreb, Croatia",
  "Zurich, Switzerland",
];
